author: Fullbridge
tagline: The Science of Working Smarter
url: http://fullbridge.com
ga-id: UA-21169274-2
serif-stack: //fonts.googleapis.com/css?family=Halant:400,700|Alegreya+SC:400,400italic,700|VT323:400
sans-stack: //fonts.googleapis.com/css?family=Source+Sans+Pro:300,300italic,700,700italic|Roboto+Condensed:400
